DATASET:
  TRAIN: "E:/projects/multi-chart/configs/train.txt"
  VAL: "E:/projects/multi-chart/configs/val.txt"
  NAMES: "configs/charts.names"
MODEL:
  NC: 1
  INPUT_WIDTH: 352
  INPUT_HEIGHT: 352
TRAIN:
  LR: 0.0005
  THRESH: 0.25
  WARMUP: true
  BATCH_SIZE: 16
  END_EPOCH: 300
  MILESTIONES:
    - 100
    - 200
    - 250
