DATASET:
  TRAIN: "configs/train_line.txt"
  VAL: "configs/val_line.txt"
  NAMES: "configs/charts.names"
MODEL:
  NC: 10
  INPUT_WIDTH: 512
  INPUT_HEIGHT: 512
TRAIN:
  LR: 0.0005
  THRESH: 0.25
  WARMUP: False
  BATCH_SIZE: 64
  END_EPOCH: 300
  MILESTIONES:
    - 100
    - 200
    - 250
