DATASET:
  TRAIN: "data/train.txt"
  VAL: "data/train.txt"
  NAMES: "configs/charts.names"
MODEL:
  NC: 3
  INPUT_WIDTH: 640
  INPUT_HEIGHT: 640
TRAIN:
  LR: 0.005
  THRESH: 0.25
  WARMUP: true
  BATCH_SIZE: 1
  END_EPOCH: 300
  MILESTIONES:
    - 100
    - 200
    - 250
